server:
  port: 80

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${mariadb_connection_string}
    username: mtdba
    password: ${mariadb_pass_development}

logging:
  level:
    root: INFO
    com.martzatech.vdhg.crmprojectback: INFO